package com.alerthub.audit.domain;

public enum AuditAction {
    TENANT_CREATED,
    TENANT_STATUS_UPDATED,
    USER_BOOTSTRAPPED,
    USER_CREATED,
    USER_STATUS_UPDATED,
    USER_LOGGED_IN,
    RULE_CREATED,
    RULE_UPDATED,
    RULE_DELETED,
    EVENT_RECEIVED,
    EVENT_REPROCESSED,
    EVENT_PROCESSED,
    EVENT_FAILED,
    NOTIFICATION_CREATED
}
